<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
function HelloWorld_block_info() {
  $blocks = array();

  //An array of blocks – each with an array – info is  one key
  $blocks['hello_world'] = array(
    'info' => t('Hello World Block'),
    );

  $blocks['hello_user'] = array(
    'info' => t('Hello User Block'),
  );

  $blocks['user_info'] = array(
    'info' => t('User Info Block'),
  );
  return $blocks;
}

function HelloWorld_block_view ($delta = '') {
  $block = array();

  switch ($delta) {

    case 'hello_world':
      $block['subject'] = t('Hello World!!!');
      $block['content'] = t('This is Hellow World!!!');
    break;


    case 'hello_world':
      $block['subject'] = t('Hello User!!!');
      Global $user;
      $block['content'] =  t('Hello @name', array(@name => $user->name));
    break;
  
  
    case 'user_info':
       $block['subject'] = t('User Info');
       $block['content'] = t('Testing!');      
       
       /*
        * to get to show up just on user profile pages
        * 
        */
       
    break;
  
  }
return $block;

}